sonar.projectKey=asancdec_UnifiedVol
sonar.organization=asancdec
sonar.projectName=UnifiedVol

sonar.sources=uv,src,examples
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build/linux-gcc-coverage/compile_commands.json
sonar.cfamily.cobertura.reportPaths=build/linux-gcc-coverage/coverage/coverage.xml

sonar.exclusions=external/**,build/**,**/vcpkg_installed/**
sonar.coverage.exclusions=tests/**,examples/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
